FROM python:3.10-slim-bookworm

COPY vmc/ /tmp/vmc/

USER root

WORKDIR /tmp/vmc/

RUN apt-get update; \
    apt-get install -y \
                   curl \
                   libssl-dev \
                   python3-pip \
                   python3-dev \
                   build-essential; \
    pip install --upgrade pip setuptools wheel; \
    pip install .;

WORKDIR /

RUN vmc collectstatic --noinput --clear;
ENTRYPOINT ["vmcctl"]
